Se crean archivos para desarrollar la primera sección de la página swipe
jojacomu/swipe pull request #1
Opened 2023-06-23 07:35 UTC by jojacomu

2023-06-23 13:53 UTC, DanielCalleCO requested changes
Se evidencia que la página que estas entregando es una copia de la página original.

No se aceptan los cambios hasta que no haya código de tu parte.

2023-07-12 19:09 UTC, DanielCalleCO requested changes

2023-07-12 19:09 UTC, DanielCalleCO commented on index.html
> +                <p>Miles de empresas de todo el mundo usan la plataforma integrada Swipe para administrar la infraestructura de transacciones financiera completra de sus negocios en línea.
```suggestion
                <p>“Miles de empresas de todo el mundo usan la plataforma integrada Swipe para administrar la completa infraestructura de las transacciones financieras de sus negocios en línea.”
```

2023-07-12 19:09 UTC, DanielCalleCO commented on style.css
> +  /* background-color: rgb(15, 161, 161); */
JJ, cuando tú vas a presentar el “trabajo final” o a crear los PR para que te revisen el código, generalmente debes borrar todas las líneas comentadas que te ayudaron a desarrollar para no entregarlas. Borra los comments innecesarios y vuelve a hacer push por fa

2023-07-14 07:25 UTC, jojacomu commented
Hola @DanielCalleCO, se hacen los ajustes solicitados.
Se cambian textos dejando los originales del modelo en el desarrollo propuesto.
Se retiran los comentarios innecesarios en el código.
Se activa diseño responsivo

2023-07-17 23:51 UTC, DanielCalleCO requested changes
Me gusta mucho como estas trabajando! Revisa los cambios que te propongo y hacemos el merge!

2023-07-17 23:51 UTC, DanielCalleCO commented on style.css
> +@media (851px <= width) {
Estas media queries en teoría son las que tu estás desarrollando en la parte superior John, entonces no tendrías que definirlas en media sino arriba.

2023-07-17 23:51 UTC, DanielCalleCO commented on style.css
> +@media (550px <= width <=768px) {
en el media query más pequeñ, te recomiendo bajarle un poquito la letra al primer título, es tan grande que se sale de la pantalla en una resolución de 320px (celular)

<img width="576" alt="image" src="https://github.com/jojacomu/swipe/assets/100431019/41986495-ec1c-4126-a0b7-60a293a779d1">

2023-07-18 04:51 UTC, jojacomu commented on style.css
> +  /* background-color: rgb(15, 161, 161); */
Se dejaron los comentarios para indicar tamaños de pantalla trabajados en la media query

2023-07-18 04:56 UTC, jojacomu commented on style.css
> +@media (851px <= width) {
Hola @DanielCalleCO, yo empece media first es decir la configuración general es para movile, no se si al resolver este comentario daño como funciona la configuración ya realizada. No se si es preciso que lo revisemos en la próxima reunión que podamos coordinar antes de iniciar este cambio solicitado.

2023-07-18 05:12 UTC, jojacomu commented on style.css
> +@media (550px <= width <=768px) {
Se hizo ajuste en estilos de h1 de la sección
![AjusteMoviles_FuenteH1](https://github.com/jojacomu/swipe/assets/131124960/faf7db2e-5fe1-4e25-a24c-81d4e7340a73)

2023-07-18 14:28 UTC, DanielCalleCO approved these changes
LGTM

2023-07-18 14:30 UTC, merged