Creación de rama para la sección 2
jojacomu/swipe pull request #2
Opened 2023-07-18 04:43 UTC by jojacomu

Hola @DanielCalleCO, para probar que entendí lo que explicaste de gestión de ramas paralelas que luego pueden ser unificadas, cree la rama para desarrollo de la sección 2 desde la rama de la sección. Aún me faltan los últimos ajustes que solicitaste para la sección 1. Por favor hazme saber si la forma como cree esta rama me permite seguir realizando el trabajo para la correspondiente sección 2.
El procedimiento que debo seguir seria:

Hago ajustes a la sección 1. 
Apruebas sección 1 en su rama.
Hago merge a main en github de la rama de la sección 1.
Hago merge a main en git (local) de la rama de la sección 1.
Elimino la rama 1 en git (local). (Hasta este paso es lo que anteriormente he usualmente realizado.)

Continuo trabajando en la rama de la sección 2 localmente hasta terminar. Genero el correspondiente pull request y espero aprobación de la misma.

Repito pasos realizados en la rama anterior para gestionar cambios y obtener aprobación de la sección 2, en paralelo Creo la rama de la sección 3 mientras espero aprobación de la sección 2 y así sucesivamente.

Siento que me hace falta un paso... creo que es hacer pull de la rama main en git hub, para igualar el repositorio local con el de la nube y garantizar que cuando me apruebes la rama de la sección 2 tenga los cambios de la rama anterior y sea agregado el código de la sección 2.  Esto se convirtió en un trabalenguas y creo que va a tocar hacer una meeting. Me cuentas si te es posible que lo revisemos mañana o tan pronto como sea posible. Gracias por tu apoyo

2023-07-18 22:13 UTC, jojacomu commented
Hola @DanielCalleCO, se implementa la sección y en revisión general se mejoraron estilos de la sección anterior. Gracias por tu asesoría

2023-07-21 15:18 UTC, DanielCalleCO commented
Revisé tu código John... te voy a hacer unas sugerencias si deseas para que se vea mejor. Vi que el fondo azul se sobrepone sobre una imagen al final... entonces edita lo que te voy a poner en el CSS y me dices si te gusta y lo subimos así.

2023-07-21 15:20 UTC, DanielCalleCO requested changes
Hazle estos cambios y me dices que tal!

2023-07-21 15:20 UTC, DanielCalleCO commented on style.css
> +    background-color: #f7f9fc;
```suggestion
   
```

2023-07-21 15:20 UTC, DanielCalleCO commented on style.css
> +    background-color: #f7f9fc;
```suggestion
    
```

2023-07-21 15:20 UTC, DanielCalleCO commented on style.css
> +    background-color: #f7f9fc;
```suggestion
    
```

2023-07-21 15:20 UTC, DanielCalleCO commented on style.css
> +    z-index: 1;
```suggestion
    z-index: -1;
```

2023-07-21 20:22 UTC, jojacomu commented on style.css
> +    background-color: #f7f9fc;
RESUELTO

2023-07-21 20:28 UTC, DanielCalleCO commented
John, me parece que la media de 320 de la sección 2 se ve como rara así con esas imagenes tan pequeñitas... por qué no pones una imagen sobre la otra?

![image](https://github.com/jojacomu/swipe/assets/100431019/46e02548-7963-4eaf-8b63-3ea9dbf8ec23)

2023-07-21 20:31 UTC, jojacomu reviewed
Cambios realizados

2023-07-21 20:31 UTC, jojacomu commented on style.css
> +    z-index: 1;
Cambio realizado

2023-07-21 20:47 UTC, jojacomu commented
Hola @DanielCalleCO se hacen los ajustes acordes a las recomendaciones recibidas.

2023-07-21 21:12 UTC, DanielCalleCO requested changes
![image](https://github.com/jojacomu/swipe/assets/100431019/23efbc91-dd16-44ff-afe7-63ed03fddc52)

Revisa por favor este boton, es Start con T

2023-07-21 21:13 UTC, DanielCalleCO commented
John, para la próxima sección, quiero que le quites el desplazamiento lateral a la página. Te lo está provocando la imagen inicial, busca la manera de que esa imagen no te desborde y en la sección 3 la arreglas

2023-07-21 23:18 UTC, jojacomu reviewed
Se hace el ajuste localmente a la palabra star por start

2023-07-24 14:36 UTC, DanielCalleCO approved these changes

2023-07-24 14:36 UTC, DanielCalleCO approved these changes
Aprobado PERO en sección 3 espero quites el desplazamiento lateral

2023-07-24 14:42 UTC, merged